[firebase]
type = "service_account"
project_id = "chatproject-6722b"
private_key_id = "your_private_key_id"
private_key = "your_private_key"
client_email = "firebase-adminsdk-fbsvc@chatproject-6722b.iam.gserviceaccount.com"
client_id = "your_client_id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40chatproject-6722b.iam.gserviceaccount.com"
